"""change avatar field to nullable

Revision ID: 2dcbc4405f08
Revises:
Create Date: 2020-03-29 19:51:01.621860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcbc4405f08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column('avatar',
                   existing_type=sa.VARCHAR(),
                   nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
