"""Add columns to user table

Revision ID: 7aa12209889a
Revises: cd54f7a26389
Create Date: 2020-03-29 17:43:28.214984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa12209889a'
down_revision = 'cd54f7a26389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('amenity')
    #op.drop_table('room_has_amenities')
    #op.add_column('room', sa.Column('air_condition', sa.Boolean(), nullable=False))
    #op.add_column('room', sa.Column('elevator', sa.Boolean(), nullable=False))
    #op.add_column('room', sa.Column('kitchen', sa.Boolean(), nullable=False))
    #op.add_column('room', sa.Column('parking', sa.Boolean(), nullable=False))
    #op.add_column('room', sa.Column('refrigerator', sa.Boolean(), nullable=False))
    #op.add_column('room', sa.Column('tv', sa.Boolean(), nullable=False))
    #op.add_column('room', sa.Column('wireless_internet', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('isHost', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('user', sa.Column('surname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_column('user', 'isHost')
    op.drop_column('user', 'isAdmin')
    op.drop_column('user', 'email')
    op.drop_column('user', 'avatar')
    op.drop_column('room', 'wireless_internet')
    op.drop_column('room', 'tv')
    op.drop_column('room', 'refrigerator')
    op.drop_column('room', 'parking')
    op.drop_column('room', 'kitchen')
    op.drop_column('room', 'elevator')
    op.drop_column('room', 'air_condition')
    op.create_table('room_has_amenities',
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('amenity_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id')
    )
    #op.create_table('amenity',
    #sa.Column('id', sa.INTEGER(), nullable=False),
    #sa.Column('description', sa.VARCHAR(length=20), nullable=False),
    #sa.PrimaryKeyConstraint('id', 'description')
    #)
    # ### end Alembic commands ###
