"""add cols to uer

Revision ID: 2282a4be4d59
Revises: 3765a9f59cb0
Create Date: 2020-05-17 01:39:21.164716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2282a4be4d59'
down_revision = '3765a9f59cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.create_unique_constraint('uq_uname', ['uname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint('uq_uname', type_='unique')
    # ### end Alembic commands ###
