"""init


Revision ID: 3765a9f59cb0
Revises: 
Create Date: 2020-05-17 01:00:10.667430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3765a9f59cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('isHost', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isHost')
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###
